- name: Checkout gh-pages branch
  uses: actions/checkout@v4
  with:
    ref: gh-pages

# Later in the job:
- name: Commit and push to gh-pages
  run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add weather.json
    git diff --cached --quiet || git commit -m "Update weather.json"
    git push origin gh-pages
